name: Pages

on:
  workflow_run:
    workflows: ["GitHub Pages"]
    types: [completed]
  pull_request:
    types: [closed]

permissions:
  actions: read
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id || github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  publish:
    uses: DioxusLabs/dioxus-ci/.github/workflows/pages-publish.yml@60c40430ef69c6d7b92439bc43e281689db1bde7
    with:
      pages-url-base: https://wheregmis.github.io
